#! /bin/bash

if [ ! -d build ]; then
	mkdir build
fi
if [ -f /lrz/sys/compilers/gcc/5.1.0/bin/gcc ];
then
	cd build && \
	cmake -C ../user.cmake \
	-DCMAKE_C_COMPILER=/lrz/sys/compilers/gcc/5.1.0/bin/gcc \
	-DCMAKE_CXX_COMPILER=/lrz/sys/compilers/gcc/5.1.0/bin/g++ \
	-DCMAKE_CXX_FLAGS="-std=c++11" \
	.. && make && cd .. && \
	[ ! -e start_server_Release ] && chmod +x start_*
else
	cd build && \
	cmake -C ../user.cmake \
	-DCMAKE_CXX_FLAGS="-std=c++11" \
	.. && make && cd .. && \
	[ ! -e start_server_Release ] && chmod +x start_*
fi
